import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from 'next/font/google';
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
export const metadata = {
  title: "SensAI",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ['latin'],
  weight: '400',  // Or the weight you're using
});
export default function RootLayout({ children }) {
  return (
    <ClerkProvider 
    appearance={{
      baseTheme:dark
    }}
    >
    <html lang="en" suppressHydrationWarning>
         <body className={`${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
         <Header/>
            <main className="min-h-screen">{children}</main>
            <Toaster richColors/>
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto text-center text-gray-200">
                <p>Made with love by SG</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
